### PR TITLE
Improve performance when zooming

### LINKED ISSUE #156: When I zoom by chartjs-plugin-zoom library, the children of tree move on the screen, and the zooming speed is very slow in the mobile size.
### Discussed in https://github.com/kurkle/chartjs-chart-treemap/discussions/155

<div type='discussions-op-text'>

<sup>Originally posted by **mirzaeianfar** October 18, 2022</sup>
When I zoom by chartjs-plugin-zoom library, the children of tree move on the screen, and the zooming speed is very slow in the mobile size.
How can I avoid moving  the items of tree  and touch speed more in mobile size?

Untitled
</div>

### PR DESCRIPTION
**Pull request by stockiNail**
Fix #156

### CODE REVIEW

**Review by kurkle — APPROVED** [review]
Nice one! This would not work with non-linear scales, but maybe there are no use cases with those anyway.

I assume you tested this locally already?

**Comment by kurkle** [comment]
Need to add performance label for this :)

**Comment by stockiNail** [comment]
@kurkle I have tested and works with wheel, drag and pinch. Also pan.

> This would not work with non-linear scales, but maybe there are no use cases with those anyway.

Probably it doesn't work anyway with no-linear scales ;)

> Need to add performance label for this :)

I was looking for that but I didn't find it therefore I tagged as improvement.

Nevertheless it's still in draft because I would suggest the following:

As I wrote, this implementation is scaling the canvas and the labels/captions could be not readable or visible also zooming.
With the previous implementation, you could see the labels with overflow: 'hidden' because the space of the element was recalculated. That said, I think it could be better to add a boolean option (maybe `scale`, default to `false`), when is set to true, it use this method, otherwise (default) use the previous one.

In this way you have another feature (I guess), to have more datasets on stacked scales.

What do you think?

**Comment by stockiNail** [comment]
@kurkle FYI I'm doing some tests to check the real improvements in terms of performance. I'm using an array with 1000 elements. more later.

**Comment by stockiNail** [comment]
@kurkle offtopic: I have seen that with many elements, `squarify` is not working well 100%! I'm going to open an issue asap.

image

**Comment by kurkle** [comment]
> @kurkle can we put the "performance" PR in the Maintenance section in the release drafter?

added

**Comment by stockiNail** [comment]
Thanks a lot!
What about new option?

**Comment by kurkle** [comment]
> As I wrote, this implementation is scaling the canvas and the labels/captions could be not readable or visible also zooming.
With the previous implementation, you could see the labels with overflow: 'hidden' because the space of the element was recalculated. That said, I think it could be better to add a boolean option (maybe scale, default to false), when is set to true, it uses this method, otherwise (default) uses the previous one.

Oh right. I don't think this will then work for the use case its trying to fix. So that would be a no for the new option. I think we need a better solution for the performance.

**Comment by stockiNail** [comment]
Ok. I”m waiting for some feedback about the use case before switching the PR ready for review in order to be sure that the slowness is related to update phase.

**Pull request closed without merging**
