### PR TITLE
Fix the rectangles size calculation aligning to bar element logic

### LINKED ISSUE #126: Evaluate to remove borderWidth configured as object
`borderWidth` option is configurable as number and as object (`{top, right, bottom, left}`).

The `borderWidth` as object enables the feature to have different `borderWidth` for each side of the box but it's adding complexity to manage other border options (like `borderRadius`) and also in the calculation of the space, both rect element and labels.

Currently the boxes with `borderWidth` as object are drawn overlapping the rectangles. This is disabling some additional border options for lineDash, joint and cap style.  

Maybe we could evaluate if makes sense to leave or remove it. Or to find out a way (maybe having a look to CHART.JS project where the `BarElement` can manage the borderWidth as object as well. Maybe `TreemapElement` can extend `BarElement`.

### PR DESCRIPTION
**Pull request by stockiNail**
FIX #126

This is PR is fixing definitely the rectangles size calculation leveraging on the copy of Chart.js `BarElement` code, where `borderWidth` (as object) and `borderRadius` are correctly managed.

This also simplifies some parts of the code and re-enables the `borderRadius` as scriptable options.

t1

### TODO

- [x] waiting for #127 and #128

### CODE REVIEW

**Review by kurkle — COMMENTED** [review]
looks great!

**Comment by stockiNail** [comment]
> looks great!

Yes definitely..  I will go on. major version or can we think to add to next minor? I dont see breaking changes till now

**Comment by kurkle** [comment]
I think this can be included in a minor

**Review by kurkle — DISMISSED** [review]

**Review by kurkle — DISMISSED** [review]

**Comment by kurkle** [comment]
needs a rebase

**Comment by stockiNail** [comment]
rebased

**Review by kurkle — APPROVED** [review]

**Comment by kurkle** [comment]
Borders look quite bad now:
image

Compared to previous: 
image

**Comment by stockiNail** [comment]
It looks like the borderColor is not applied

**Comment by stockiNail** [comment]
There is a line that it should not be there too

**Comment by kurkle** [comment]
I think the border was previously drawn over background, hence different color. But the artifact are due to devicePixelRatio and canvas weirdness with clipping.

**Comment by stockiNail** [comment]
> I think the border was previously drawn over background, hence different color.

Yes, this morning I thought it. Nevertheless it could be a breaking change, even if this logic sounds correct to me because it maintains the `borderColor` of the config... Apologize if I didn't recognize before.

**Pull request merged**
