### PR TITLE
Resolve dataset options (can be scriptable)

### PR DESCRIPTION
**Pull request by kurkle**
Couple of fixtures fail locally (no spriting)

TODO:

- [ ] add tests

### CODE REVIEW

**Comment by kurkle** [comment]
Actually not going to add any tests at this point, because none of the options make sense as scriptable currently.

The caption options are resolved in 2 places (dataset and element), and the first one determines the space while the 2nd one does the drawing. The should be merged somehow. Same story with borderWidth.

So this would need further refactoring.

**Comment by stockiNail** [comment]
@kurkle I agree. Believe me that I thought several times about that (I don't like it). I was thinking to move the size of the rect calculation after element creation but the buildData should be reviewed completely.

**Comment by kurkle** [comment]
Agreed about the buildData. I think it should be merged with element creation, and the available child rect calculation moved to element. 

Something like
- determine main rect
- parse and create elements on this level
- recurse

So actually quite much the same as the buildData, expect createting elements on the fly.

Label that a breaking change and do it in a major version. Maybe start using `data` instead of `tree`

**Comment by stockiNail** [comment]
> So actually quite much the same as the buildData, expect createting elements on the fly.

exactly! 

> Label that a breaking change and do it in a major version. Maybe start using `data` instead of `tree`

I'll open an issue (tomorrow), if you agree, in order to do not forget for version 3.0.

**Comment by stockiNail** [comment]
Before closing my laptop, I preferred to submit the issue (I have also created the milestone 3.0.0 and added "braking change" label because missing).

**Pull request closed without merging**
