### PR TITLE
Fix borders and spacing on high dpr displays

### PR DESCRIPTION
**Pull request by kurkle**

### CODE REVIEW

**Comment by stockiNail** [comment]
Therefore it was related to dpr?

**Comment by kurkle** [comment]
> Therefore it was related to dpr?

yes, it is. this is still not good enough though.

**Comment by stockiNail** [comment]
Apologize but this evening I was busy.
I was thinking to fallback to the previous logic drawing border over the background.
Anyway I dont understand how it could work in chartjs for the bars

**Comment by stockiNail** [comment]
I have also to admit that I will never discover it was related to dpr…

**Comment by kurkle** [comment]
# borderWidth: 0.5

## DPR=1
image

## DPR=2
image

**Comment by kurkle** [comment]
ok, fixed the borderWidth: 0.5, dpr=1 case
image

image

Still got some issue with rtl

image

image

**Comment by stockiNail** [comment]
It looks like a very annoying issue... but FMI, what do you think it has generated this issue? Some updates? was always there?

**Comment by kurkle** [comment]
> It looks like a very annoying issue... but FMI, what do you think it has generated this issue? Some updates? was always there?

Looks like it broke (for docs) in this commit: https://github.com/kurkle/chartjs-chart-treemap/commit/9deba20de5e9a528bf3830ec7935a9e728c09684

I guess it is some change in Chart.js from 3.7.0 to 3.9.1

**Comment by stockiNail** [comment]
> EDIT: oops, I thought this was a discussion in issue #146

:D

**Pull request merged**
