### PR TITLE
Add element scope to controller options

### PR DESCRIPTION
**Pull request by stockiNail**
This PR is addressing the issue related to the usage of element options to squarify the data. Currently the controller is using the configuration of the dataset, without any fallback, ignoring possible configuration and re-applying the defaults.

This is a deviation from the CHART.JS scopes chain from [Dataset level options](https://www.chartjs.org/docs/latest/general/options.html#dataset-level-options) to [Dataset element level options](https://www.chartjs.org/docs/latest/general/options.html#dataset-element-level-options).

### CODE REVIEW

**Comment by kurkle** [comment]
So adding the `element.treemap` to dataset resolution path for `borderWidth`, which still can not be scriptable?
How about moving the `borderWidth` to dataset level instead?

**Comment by kurkle** [comment]
Oh and `captions`

**Comment by stockiNail** [comment]
> So adding the `element.treemap` to dataset resolution path for `borderWidth`, which still can not be scriptable?

Yes it can but it will get the context.type = 'dataset' and not 'data' because it the controller options doesn't have the element context. Maybe we could update it with missing information and setting data as type.

> How about moving the `borderWidth` to dataset level instead?

Moving borderWidth to dataset level, we:

1. create a breaking change (but that's not a big issue, we can wait for major release)
2. you can not set at element level like all other styling options

And as you wrote, we have also the captions.

**Comment by stockiNail** [comment]
there are also `spacing` and `rtl`but in my opinion these options should be moved to dataset level because they should be the same for all elements. But breaking changes therefore for next major version.

**Comment by kurkle** [comment]
For properly handled element level, the captions, borderWidth etc should be resolved for each element while squarifying, and for the context to be correct, the element needs to be created before that. So the elements would need to be created while squarifying, and we would need to squarify on every update, because some borderWidth or font size could have changed.

So in my opinion, the square size affecting properties should be resolved at dataset level (borderWidth, caption font) and not be customisable for each rect. Colors could still be changed though.

Improving that we could create a context per "level", (still resolving in dataset/squarify), which would probably work for most use cases I can think of.

This would need to be in v3 ofc.

**Comment by stockiNail** [comment]
> For properly handled element level, the captions, borderWidth etc should be resolved for each element while squarifying, and for the context to be correct, the element needs to be created before that. So the elements would need to be created while squarifying, and we would need to squarify on every update, because some borderWidth or font size could have changed.

Fully agree

> So in my opinion, the square size affecting properties should be resolved at dataset level (borderWidth, caption font) and not be customisable for each rect. Colors could still be changed though.

For instance, that means we will have some options of the `captions` resolved at dataset level (`display`, `font`), and others at element one (`color`, `formatter`). Maybe it's better to move the whole captions at dataset level, to avoid any confusion. I know, it's a constraint and limitation. 
For `borderWidth`, we can do the same even if for my poor mindset, borderWidth is a typical option of an element. :(

> This would need to be in v3 ofc.

OKI!

**Comment by kurkle** [comment]
> For borderWidth, we can do the same even if for my poor mindset, borderWidth is a typical option of an element. :(

I agree with you that it is typical. Maybe there are more ways to do it, let's keep thinking.

**Comment by stockiNail** [comment]
I don't give up, sorry for you ;)

**Comment by stockiNail** [comment]
Different `borderWidth `(but for all element options, like `captions`, `font`, `padding`) for each element:

image

### Dataset config

```javascript
datasets: [{
  tree: objectsTree,
  key: 'value',
  groups: [0, 1, '_name'],
  borderWidth(ctx) { // <- scriptable option for ctx.data (no dataset)
    if (ctx.type !== 'data') {
      return 0;
    }
    return ctx.raw.l ? ctx.raw.l * 5 + 3 : 2;
  },
  borderColor: '#FF8F00',
  backgroundColor: 'rgba(255,167,38,0.3)',
  captions: {
    align: 'center',
  },
  labels: {
    display: true,
    formatter: (ctx) => {
      return ctx.raw.v;
    },
  }
}]
```

### Code

I'm afraid to push it.... :)

**Comment by stockiNail** [comment]
I have pushed the code. Be aware that the PR is anyway not completed because documentation and types are not updated yet.

**Comment by stockiNail** [comment]
@kurkle I forgot to write that in this way ALL options are scriptable

**Comment by kurkle** [comment]
No, I don't want to go this way. The context here is missing the element as you said, but also is not preserved like usual.
But the main issue is the altered resolution order, which would make things even more confusing for users.
So I will have this fixed properly in v3.

**Pull request closed without merging**
