### PR TITLE
Fix defaults value of the options on the documentation

### LINKED ISSUE #129: Mismatch between documentation and element defaults
Some options are reported with a wrong default in the documentation (i.e. `labels.color`).

### PR DESCRIPTION
**Pull request by stockiNail**
Fix #129

This PR orders the options alphabetically.

### TODO

- [x] waiting for PR #127 where the `spriteText` is applied on test case

### CODE REVIEW

**Comment by stockiNail** [comment]
I have a doubt if it's a breaking change, due to the change of `color` options default. It shouldn't...

**Comment by kurkle** [comment]
> I have a doubt if it's a breaking change, due to the change of `color` options default. It shouldn't...

Technically it is. Maybe its better to update docs to `'black'` and change the defaults in v3

**Comment by stockiNail** [comment]
Yes fully agree

**Comment by stockiNail** [comment]
> Maybe its better to update docs to `'black'` and change the defaults in v3

Done

**Review by kurkle — APPROVED** [review]

**Pull request merged**
